Updated Readme with Examples
mikeal/watch pull request #124
Opened 2017-02-09 10:32 UTC by Burgi0101

Added examples for Terminal & NPM Script usage including Windows support!

2017-03-26 20:35 UTC, levithomason requested changes

2017-03-26 20:35 UTC, levithomason commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
Whoops, escaping looks like it was missed here.

2017-03-28 06:43 UTC, Burgi0101 commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
I think escaped quotationmarks are just not shown excaped on github!

2017-03-28 06:45 UTC, levithomason commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
Looks like they are missing in the raw as well:

![image](https://cloud.githubusercontent.com/assets/5067638/24392147/819ef86c-1347-11e7-87f3-e0559fbefc52.png)

https://raw.githubusercontent.com/mikeal/watch/fad8de91b5aedea105f336acd4171a10beb805a9/README.md

2017-03-28 06:46 UTC, levithomason commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
Perhaps they got removed on commit somehow?  Do you see them locally?

2017-03-28 07:00 UTC, Burgi0101 commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
I have to check this, I am currently on my phone! Will try to commit again with escaped double quotes and then we'll see whats the issue!
Thx for pointing this out!

2017-03-28 07:00 UTC, levithomason commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
No worries my first comment was on my phone and I also hesitated at first :P

2017-03-28 08:01 UTC, Burgi0101 commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
yeah it's just not shown in the GUI here!

2017-03-29 04:06 UTC, levithomason commented on README.md
> +        "watch:windows": "watch "npm run test -s" source",
well, I cannot pull the branch as GitHub doesn't know where the repo is:

![image](https://cloud.githubusercontent.com/assets/5067638/24438130/0cc3625e-13fa-11e7-9979-72a6336bb12a.png)


But, if I down the raw file, I get this:

![image](https://cloud.githubusercontent.com/assets/5067638/24438149/3a68d8c4-13fa-11e7-8ac3-c2ccc22b79b1.png)

I've never seen the unknown repo thing before, but, perhaps it is related.  What is clear is that the changes in this PR do not include escaped quotes.

2017-08-20 15:17 UTC, levithomason commented
Just merged this in #135.

2017-08-20 15:17 UTC, closed without merging